source 'http://rubygems.org'

gem 'rails', '3.2.13'

gem "rake", "~> 10.0.4"

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :production do
  gem 'mysql2'
  gem 'yaml_db'
end

group :development do
  gem 'sqlite3'
  gem "better_errors"
  gem "binding_of_caller"
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

#IHM
gem 'jquery-rails', "2.3.0"
gem 'jquery-ui-rails'
gem "font-awesome-rails"
gem 'bootstrap_form'

gem "will_paginate"
gem "will_paginate-bootstrap"
gem "masonry-rails", :git =>"https://github.com/descl/masonry-rails.git" #items alignment


#Semantic Web
gem "rest-client"
gem "sparql-client", :github => 'descl/sparql-client'#, "~> 1.0.4.1"
gem "rdf-virtuoso", "~> 0.1.1"

#authentification
gem 'devise'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem "devise_mailchimp", :git => "https://github.com/jcnnghm/devise_mailchimp"  # Last officially released gem
gem "hominid", :git =>"https://github.com/descl/hominid.git"
#gem "cancan" #rights managment

#opml files import
gem 'opml_saw', :git => "git://github.com/feedbin/opml_saw.git", :branch => "master"
gem "paperclip", "~> 3.4.1"
gem "remotipart", "~> 1.2.1" #load files with Ajax



gem 'rvm-capistrano'

#internationalization
gem 'rails-i18n' #in order to have activerecord translations
gem 'i18n-js', :github => 'fnando/i18n-js'
gem 'devise-i18n'

gem "stathat", "~> 0.1.7"
gem 'whenever'





gem "capit", "~> 0.3.3"
