source 'https://rubygems.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'

#gem "linkeddata"
gem "rest-client"
gem "sparql-client", "~> 0.3.1"
gem "rdf-virtuoso", "~> 0.1.1"

#for variables parsing other javascript
gem "gon"

gem "will_paginate"

gem 'devise'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'

#opml files import
gem 'opml_saw', github: 'feedbin/opml_saw'
gem "paperclip", "~> 3.4.1"

gem "tag_it", "~> 0.0.1"